name: Test Webpage Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-opencv
        pip install matplotlib selenium webdriver-manager scikit-image

    - name: Run change detection test
      run: python test_changes.py

    - name: Archive test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: failed-test-images
        path: screenshots/
